### PR TITLE
[TT-7185]Performance Improvement

### PR DESCRIPTION
**Pull request by zalbiraw**
Change sync and publish logic to run more efficiently. 

Instead of fetching the entire list of APIs/Policies every time we create an API/Policy. We are fetching once and maintaining the diff as we create more objects. 

Instead of searching through all the existing APIs/Policies for each API/Policy we are creating/updating. The existing list of objects is parsed into maps based on the fields we are testing against (APIID, Id, Slug, and Listen Path + Domain for the APIs and MID and ID for the policies.) Those lists are updated as objects are created/updated.

This should reduce time complexity from 

N * M * M + M * P to N + M + P

where, 
N is the number of new objects (APIs or Policies)
M is the number of existing objects 
P is the payload cost for fetching the entire list of existing objects

### CODE REVIEW

**Comment by zalbiraw** [comment]
@tbuchaillot you're a legend!

**Review by mativm02 — APPROVED** [review]
amazing job @zalbiraw!

**Review by sredxny — APPROVED** [review]
lgtm

@tbuchaillot am wondering, why are we using `fmt` instead a logger in the application?

**Pull request merged**
